---
- hosts: aws_ec2
  user: ec2-user
  become: yes
  connection: ssh

  vars:
    ansible_ssh_private_key_file: "/etc/ansible/london.pem"
    ansible_ssh_user: "ec2-user"

  tasks:
    - name: installing git 
      yum: name=git state=present
    - name: installing webserver
      yum: name=httpd state=present
    - name: restart web server
      service: name= httpd state=restarted
    - name: getting code
      git:
        repo:
        dest: "/var/www/html/"
        version: "frontend"
...

